### ISSUE TITLE
Access Violation When Reopening MDI Child Form with TMariaDBConnection Instance

### ISSUE THREAD

**Issue by ralfbertoldi** [AliDehbansiahkarbon/EasyDBMigrator#11]
I encountered an issue while using EasyDBMigrator with the sample project projects\MariaDB\simple.

Steps to Reproduce:

I created an MDI parent form (UMDIMain.pas).
I modified the sample form UMain.pas to be an MDI child.
In the UMain.pas form, I added Action := caFree; to the OnClose event.
Problem:
The MDI child (TfrmMain) works fine when it is opened the first time.
However, when I close the child form and open it again, I get an access violation error.
The error seems to be related to the instance management of TMariaDBConnection.

Example Code:

```
program EasyDB_MariaDB_Simple;
uses
  Vcl.Forms,
  UMain in 'UMain.pas' {frmMain},
  UMDIMain in 'UMDIMain.pas' {frmMDIMain};

{$R *.res}

begin
  Application.Initialize;
  Application.MainFormOnTaskbar := True;
  Application.CreateForm(TfrmMDIMain, frmMDIMain);
  Application.Run;
end.

```
UMDIMain.pas

```
unit UMDIMain;
interface
uses
  Winapi.Windows, Winapi.Messages, System.SysUtils, System.Variants, System.Classes, Vcl.Graphics,
  Vcl.Controls, Vcl.Forms, Vcl.Dialogs, Vcl.Menus;
type
  TfrmMDIMain = class(TForm)
    MainMenu1: TMainMenu;
    options1: TMenuItem;
    starteasydb1: TMenuItem;
    exit1: TMenuItem;
    procedure exit1Click(Sender: TObject);
    procedure starteasydb1Click(Sender: TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end;
var
  frmMDIMain: TfrmMDIMain;
implementation
{$R *.dfm}
uses UMain;

procedure TfrmMDIMain.exit1Click(Sender: TObject);
begin
  Close;
end;

procedure TfrmMDIMain.starteasydb1Click(Sender: TObject);
begin
  Application.CreateForm(TfrmMain, frmMain);
end;

end.

```

Additional Information:
It seems the issue arises from the TMariaDBConnection instance not being properly handled when the form is closed and reopened. I suspect this might be related to how TMariaDBConnection handles its singleton instance.

Could you please provide guidance on how to handle the connection instance properly when dealing with MDI child forms, or let me know if this is a known issue?

Thank you!

**Comment by AliDehbansiahkarbon** [comment]
Hi,
I wasn't aware of this issue.
Would you please send me a zip folder of your sample project?
Here or via email: adehban@gmail.com
I will try to fix it.

Best regards,
Ali.

**Comment by AliDehbansiahkarbon** [comment]
Fixed.
Please pull the library one more time.
