### ISSUE TITLE
D10.2.3 compiling

### ISSUE THREAD

**Issue by limelect** [AliDehbansiahkarbon/EasyDBMigrator#4]
I do not have on my D10.2.3 (paid one)
FireDAC.Phys.MSSQLDef or FireDAC.Phys.MSSQL
All I have is
FireDAC.Phys
FireDAC.Phys.SQLGenerator
FireDAC.Phys.SQLPreprocessor
Any help?

**Comment by AliDehbansiahkarbon** [comment]
Unfortunately, MSSQL drivers are **unavailable** in the CE(**community edition**), If you **don't** need MSSQL-related functionalities you can comment or remove them all, and then you will be able to compile because the rest (MySQL, MariaDB, PostgreSQL, etc.) are available in CE.

**Comment by limelect** [comment]
No my 10.2.3 **IS NOT CE community edition.** It is a paid
with license one.

**Comment by AliDehbansiahkarbon** [comment]
Sorry, I didn't get your point correctly.
Well, I think I can't help with this, unfortunately, this file shouldn't be missing with a paid RAD Studio, I think you should try to get support from Embarcadero.
