### ISSUE TITLE
AV Exception if not check  Assigned(FConfig.ProgressBar) 

### ISSUE THREAD

**Issue by hp1361** [AliDehbansiahkarbon/EasyDBMigrator#9]
https://github.com/AliDehbansiahkarbon/EasyDBMigrator/blob/3c9dab45219a6b972f25f60bf220c7f0c950eea1/Lib/Runners/EasyDB.Runner.pas#L356

**Comment by AliDehbansiahkarbon** [comment]
Hi, 
Could you provide me with more explanation?
Which sample project raises this exception?

As I checked there is an "if Assigned()" line: 

![image](https://github.com/AliDehbansiahkarbon/EasyDBMigrator/assets/5601608/f487b44d-4a10-4809-ba07-2ca5dd62849c)

**Comment by AliDehbansiahkarbon** [comment]
And something else that I would like to mention is that this is not the best practice to update the main thread (UI), this is just a demonstration in some quick samples to show you how it works.
In a real project, I strongly suggest you use "messages" for communications between side threads and the main thread. (PostMessage, SendMessage)

**Comment by hp1361** [comment]
You are right
The condition is checked
Because it was installed from Getit, the old version was running
I installed it manually and the problem was solved

I don't use progress bar at all and that's why the error message was surprising

Thank you and EasyDBMigrator library
